sensor:
  - platform: example
  - platform: random
    name: Heißwasserzähler
    minimum: 0
  - platform: random
    name: Kaltwasserzähler
    minimum: 0
    
updater:
  
light:
  - platform: livolo
    devices:
      1:
        name: Wohnzimmer
      2:
        name: Büro
  - platform: hyperion
	   
automation: !include automation.yaml

mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      persistence_file: 'path/mysensors.json'
      baud_rate: 38400
    - device: '/dev/ttyACM0'
      persistence_file: 'path/mysensors2.json'
      baud_rate: 115200
    - device: mqtt
      persistence_file: 'path/mysensors3.json'
      topic_in_prefix: 'mygateway1-out'
      topic_out_prefix: 'mygateway1-in'
  debug: true
  optimistic: false
  persistence: true
  retain: true
  version: 2.0