kindle60f73653dfritzbox:
  hide_if_away: false
  mac: F0:27:2D:F4:77:F7
  name: kindle-60f73653d.fritz.box
  picture: null
  track: false

fritzbox:
  hide_if_away: false
  mac: 24:65:11:D8:61:B0
  name: fritz.box
  picture: null
  track: false

raspberrypifritzbox:
  hide_if_away: false
  mac: B8:27:EB:93:DA:F7
  name: raspberrypi.fritz.box
  picture: null
  track: false

#android2e7650c3b449d07afritzbox:
#  hide_if_away: false
#  mac: 88:07:4B:AF:57:97
#  name: Florian
#  picture: null
#  track: true

desktop008l2lv:
  hide_if_away: false
  mac: D0:50:99:80:C6:8A
  name: DESKTOP-008L2LV
  picture:
  track: false

hassbian:
  hide_if_away: false
  mac: B8:27:EB:86:FA:7B
  name: HASSbian
  picture:
  track: false

md1a021c:
  hide_if_away: false
  mac: 6C:88:14:BD:14:60
  name: MD1A021C
  picture:
  track: false

yeelightone:
  hide_if_away: false
  mac: F0:B4:29:A8:F1:6E
  name: YeelightOne
  picture:
  track: false

android6092e470d062553a:
  hide_if_away: false
  mac: F4:42:8F:AF:46:41
  name: android-6092e470d062553a
  picture:
  track: false

homeassistant:
  hide_if_away: false
  mac: B8:27:EB:D3:AF:2E
  name: homeassistant
  picture:
  track: false

androidc3f83901d5fc76cd:
  hide_if_away: false
  mac: F8:32:E4:05:F4:3F
  name: android-c3f83901d5fc76cd
  picture:
  track: false

phone_phone:
  hide_if_away: false
  mac: 88:07:4B:AF:57:97
  name: Flo Phone
  picture:
  track: true

frafultrabook:
  hide_if_away: false
  mac: E0:06:E6:42:1D:18
  name: fraf-Ultrabook
  picture:
  track: true

pc19216817833:
  hide_if_away: false
  mac: 4C:17:EB:F1:AF:03
  name: PC-192-168-178-33
  picture:
  track: true

txnr636:
  hide_if_away: false
  mac: 00:09:B0:D4:76:0D
  name: TX-NR636
  picture:
  track: true

pc19216817849:
  hide_if_away: false
  mac: 7C:B2:32:42:EF:51
  name: PC-192-168-178-49
  picture:
  track: true

android6dd65f7c46cfcd33:
  hide_if_away: false
  mac: 78:4B:87:C2:8E:C5
  name: android-6dd65f7c46cfcd33
  picture:
  track: true

android720854bcd352a156:
  hide_if_away: false
  mac: 8C:3A:E3:73:74:96
  name: android-720854bcd352a156
  picture:
  track: true

md1kv02c:
  hide_if_away: false
  mac: D0:57:7B:03:47:65
  name: MD1KV02C
  picture:
  track: true

hpdrucker:
  hide_if_away: false
  mac: 70:56:81:8F:60:BB
  name: HP-Drucker
  picture:
  track: true

androidecde48b833838b87:
  hide_if_away: false
  mac: 84:9F:B5:03:76:77
  name: android-ecde48b833838b87
  picture:
  track: true

amazon60f73653d:
  hide_if_away: false
  mac: 74:C2:46:8E:17:C4
  name: amazon-60f73653d
  picture:
  track: true

raspberrypi:
  hide_if_away: false
  mac: 00:0F:60:0C:E7:A8
  name: raspberrypi
  picture:
  track: true

androidce74bc49108cda1c:
  hide_if_away: false
  mac: 34:FC:EF:A0:5E:D1
  name: android-ce74bc49108cda1c
  picture:
  track: true

pc19216817842:
  hide_if_away: false
  mac: 00:01:E6:A4:4E:32
  name: PC-192-168-178-42
  picture:
  track: true

pc19216817834:
  hide_if_away: false
  mac: 7C:ED:8D:64:1F:46
  name: PC-192-168-178-34
  picture:
  track: true
  vendor: Microsoft

pc19216817837:
  hide_if_away: false
  mac: 00:16:6C:46:33:91
  name: PC-192-168-178-37
  picture:
  track: true
  vendor: Samsung Electronics Co.,Ltd

androidcca318c694afbf66:
  hide_if_away: false
  mac: 10:FA:CE:2C:67:8F
  name: android-cca318c694afbf66
  picture:
  track: true
  vendor: Reacheng Communication Technology Co.,Ltd

androida346641fe5237c6c:
  hide_if_away: false
  mac: 2C:59:8A:5D:0D:A4
  name: android-a346641fe5237c6c
  picture:
  track: true
  vendor: LG Electronics (Mobile Communications)

android2cc1e1b6fa43325d:
  hide_if_away: false
  mac: 40:F3:08:53:0B:6B
  name: android-2cc1e1b6fa43325d
  picture:
  track: true
  vendor: Murata Manufacturing Co., Ltd.

pc19216817851:
  hide_if_away: false
  mac: 50:F5:DA:C4:A4:74
  name: PC-192-168-178-51
  picture:
  track: true
  vendor: Amazon Technologies Inc.

laurapc:
  hide_if_away: false
  mac: 0C:60:76:99:AB:BC
  name: Laura-PC
  picture:
  track: true
  vendor: Hon Hai Precision Ind. Co.,Ltd.

pc19216817830:
  hide_if_away: false
  mac: 70:9E:29:0E:F5:34
  name: PC-192-168-178-30
  picture:
  track: true
  vendor: Sony Interactive Entertainment Inc.

md1kv02c_2:
  hide_if_away: false
  mac: 30:E1:71:82:9D:A9
  name: MD1KV02C
  picture:
  track: true
  vendor: Hewlett Packard

amazon122b6e537:
  hide_if_away: false
  mac: 40:B4:CD:20:4F:1F
  name: amazon-122b6e537
  picture:
  track: true
  vendor: Amazon Technologies Inc.

androidcc98f00eed77d9f2:
  hide_if_away: false
  mac: 48:5A:3F:45:E5:24
  name: android-cc98f00eed77d9f2
  picture:
  track: true
  vendor: WISOL
