- platform: command_line
  switches:
    home_assistant_system_shutdown:
      command_off: "/usr/sbin/poweroff"
- platform: broadlink
  host: 192.168.178.65
  mac: 34:EA:34:B5:18:C9
  switches: !include switches_broadlink.yaml